version: "3.8"
services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/devops1-tp-back
    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/devops1-tp
      - /usr/devops1-tp/node_modules
    command: ["npm", "start"]
