version: "3.8"
services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/devops1-tp-back
    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/devops1-tp
      - /usr/devops1-tp/node_modules
    command: ["npm", "start"]

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: devops1
      POSTGRES_USER: devops1
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
