version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/devops1-tp
      - /usr/devops1-tp/node_modules
    command: ["npm", "start"]
